export const LOGIN_ADD_REQUEST = "LOGIN_ADD_REQUEST";
export const LOGIN_ADD_SUCCESS = "LOGIN_ADD_SUCCESS";
export const LOGIN_ADD_FAIL = "LOGIN_ADD_FAIL";
export const LOGIN_ADD_RESET = "LOGIN_ADD_RESET";


export const SIGNUP_ADD_REQUEST = "SIGNUP_ADD_REQUEST";
export const SIGNUP_ADD_SUCCESS = "SIGNUP_ADD_SUCCESS";
export const SIGNUP_ADD_FAIL = "SIGNUP_ADD_FAIL";
export const SIGNUP_ADD_RESET = "SIGNUP_ADD_RESET";

export const ORDER_ADD_REQUEST = "ORDER_ADD_REQUEST";
export const ORDER_ADD_SUCCESS = "ORDER_ADD_SUCCESS";
export const ORDER_ADD_FAIL = "ORDER_ADD_FAIL";
export const ORDER_ADD_RESET = "ORDER_ADD_RESET";